web:
  image: kushki/magento1.9
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - env
mysql:
  image: mysql:5.6.23
  env_file:
    - env
  volumes:
    - ./Kushkiplugin:/tmp/local

