<?php
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
$publicId = Mage::helper('core')->decrypt(Mage::getStoreConfig('payment/kushkipayment/commercepublic'));
?>
<h2>Kushki</h2>

<form id="kushki-kushkipayment-form" action="<?php echo Mage::helper('kushkipayment')->getPaymentGatewayUrl(); ?>" method="post">
    <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
    <input type="hidden" name="grandTotal" value="<?php echo number_format($order->base_grand_total,2); ?>">
</form>

<script src="https://uat.aurusinc.com/kushki/kushki/kushki-checkout.js" charset="utf-8"></script>
 
<script type="text/javascript">
    var kushki = new KushkiCheckout({
        "form" : 'kushki-kushkipayment-form',
        "merchant_id" : '<? echo $publicId; ?>',
        "amount" : '<? echo number_format($order->base_grand_total,2); ?>'
    });
</script>